package:
  name: "doglib"
  version: "0.1.2"

about:
  summary: "Doglib ist eine Python-Bibliothek, die speziell entwickelt wurde, um Schülerinnen die grundlegenden Arbeitsprinzipien von Python-Bibliotheken auf einfache und unterhaltsame Weise zu erklären."

source:
  path: ..
  
build:
  noarch: python